import Footer from '@/components/Footer'
import Nav from '../components/Nav'
import './globals.css'


export const metadata = {
  title: 'Best travel',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='px-10'>
        <Nav></Nav>
        {children}
        <Footer></Footer>
      </body>
    </html>
  )
}
